
kind: pipeline
name: run

steps:
  - name: install_and_build
    image: python:3.6-slim
    commands:
      - python3 setup.py sdist bdist_wheel

  - name: pypi_publish
    image: plugins/pypi
    settings:
      username:
        from_secret: pypi_username
      password:
        from_secret: pypi_password
      # repository: https://test.pypi.org/legacy/
    when:
      branch:
        - master
